export default {
  state: {
    keys: [
      { type: 'white', name: 'c2', tag: 'do', color: '#99CC33', key: '1' },
      { type: 'black', name: 'cs2', key: '!', color: '#99CC99' },
      { type: 'white', name: 'd2', tag: 're', color: '#99CC33', key: '2' },
      { type: 'black', name: 'ds2', key: '@', color: '#99CC99' },
      { type: 'white', name: 'e2', tag: 'mi', color: '#99CC33', key: '3' },
      { type: 'white', name: 'f2', tag: 'fa', color: '#99CC33', key: '4' },
      { type: 'black', name: 'fs2', key: '$', color: '#99CC99' },
      { type: 'white', name: 'g2', tag: 'so', color: '#99CC33', key: '5' },
      { type: 'black', name: 'gs2', key: '%', color: '#99CC99' },
      { type: 'white', name: 'a2', tag: 'la', color: '#99CC33', key: '6' },
      { type: 'black', name: 'as2', key: '^', color: '#99CC99' },
      { type: 'white', name: 'b2', tag: 'si', color: '#99CC33  ', key: '7' },
      { type: 'white', name: 'c3', tag: 'do', color: '#FFCCCC', key: '8' },
      { type: 'black', name: 'cs3', key: '*', color: '#FF9999' },
      { type: 'white', name: 'd3', tag: 're', color: '#FFCCCC', key: '9' },
      { type: 'black', name: 'ds3', key: '(', color: '#FF9999' },
      { type: 'white', name: 'e3', tag: 'mi', color: '#FFCCCC', key: '0' },
      { type: 'white', name: 'f3', tag: 'fa', color: '#FFCCCC', key: 'q' },
      { type: 'black', name: 'fs3', key: 'Q', color: '#FF9999' },
      { type: 'white', name: 'g3', tag: 'so', color: '#FFCCCC', key: 'w' },
      { type: 'black', name: 'gs3', key: 'W', color: '#FF9999' },
      { type: 'white', name: 'a3', tag: 'la', color: '#FFCCCC', key: 'e' },
      { type: 'black', name: 'as3', key: 'E', color: '#FF9999' },
      { type: 'white', name: 'b3', tag: 'si', color: '#FFCCCC', key: 'r' },
      { type: 'white', name: 'c4', tag: 'do', color: '#FFFF99', key: 't' },
      { type: 'black', name: 'cs4', key: 'T', color: '#FFCC00' },
      { type: 'white', name: 'd4', tag: 're', color: '#FFFF99', key: 'y' },
      { type: 'black', name: 'ds4', key: 'Y', color: '#FFCC00' },
      { type: 'white', name: 'e4', tag: 'mi', color: '#FFFF99', key: 'u' },
      { type: 'white', name: 'f4', tag: 'fa', color: '#FFFF99', key: 'i' },
      { type: 'black', name: 'fs4', key: 'I', color: '#FFCC00' },
      { type: 'white', name: 'g4', tag: 'so', color: '#FFFF99', key: 'o' },
      { type: 'black', name: 'gs4', key: 'O', color: '#FFCC00' },
      { type: 'white', name: 'a4', tag: 'la', color: '#FFFF99', key: 'p' },
      { type: 'black', name: 'as4', key: 'P', color: '#FFCC00' },
      { type: 'white', name: 'b4', tag: 'si', color: '#FFFF99', key: 'a' },
      { type: 'white', name: 'c5', tag: 'do', color: '#CCCCFF', key: 's' },
      { type: 'black', name: 'cs5', key: 'S', color: '#9999CC' },
      { type: 'white', name: 'd5', tag: 're', color: '#CCCCFF', key: 'd' },
      { type: 'black', name: 'ds5', key: 'D', color: '#9999CC' },
      { type: 'white', name: 'e5', tag: 'mi', color: '#CCCCFF', key: 'f' },
      { type: 'white', name: 'f5', tag: 'fa', color: '#CCCCFF', key: 'g' },
      { type: 'black', name: 'fs5', key: 'G', color: '#9999CC' },
      { type: 'white', name: 'g5', tag: 'so', color: '#CCCCFF', key: 'h' },
      { type: 'black', name: 'gs5', key: 'H', color: '#9999CC' },
      { type: 'white', name: 'a5', tag: 'la', color: '#CCCCFF', key: 'j' },
      { type: 'black', name: 'as5', key: 'J', color: '#9999CC' },
      { type: 'white', name: 'b5', tag: 'si', color: '#CCCCFF', key: 'k' },
      { type: 'white', name: 'c6', tag: 'do', color: '#CCFFFF', key: 'l' },
      { type: 'black', name: 'cs6', key: 'L', color: '#99CCFF' },
      { type: 'white', name: 'd6', tag: 're', color: '#CCFFFF', key: 'z' },
      { type: 'black', name: 'ds6', key: 'Z', color: '#99CCFF' },
      { type: 'white', name: 'e6', tag: 'mi', color: '#CCFFFF', key: 'x' },
      { type: 'white', name: 'f6', tag: 'fa', color: '#CCFFFF', key: 'c' },
      { type: 'black', name: 'fs6', key: 'C', color: '#99CCFF' },
      { type: 'white', name: 'g6', tag: 'so', color: '#CCFFFF', key: 'v' },
      { type: 'black', name: 'gs6', key: 'V', color: '#99CCFF' },
      { type: 'white', name: 'a6', tag: 'la', color: '#CCFFFF', key: 'b' },
      { type: 'black', name: 'as6', key: 'B', color: '#99CCFF' },
      { type: 'white', name: 'b6', tag: 'si', color: '#CCFFFF', key: 'n' },
      { type: 'white', name: '-', tag: '-', color: '#CCCCCC', key: 'm' },
    ],
  },
};
